$('#ver_monitoreo_correo').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Botón que activó el modal
  var mc_tipo_herramienta = button.data('mc_tipo_herramienta')
  var mc_fecha_monitoreo = button.data('mc_fecha_monitoreo')
  var mc_linea = button.data('mc_linea')
  var mc_fecha_correo = button.data('mc_fecha_correo')
  var mc_hora_correo = button.data('mc_hora_correo')
  var mc_requerimiento_cliente = button.data('mc_requerimiento_cliente')
  var mc_observaciones_monitoreo = button.data('mc_observaciones_monitoreo')
  var mc_id_scriba = button.data('mc_id_scriba')
  var mc_id_envio = button.data('mc_id_envio')
  var mc_pregunta_1 = button.data('mc_pregunta_1')
  var mc_pregunta_2 = button.data('mc_pregunta_2')
  var mc_pregunta_3 = button.data('mc_pregunta_3')
  var mc_pregunta_4 = button.data('mc_pregunta_4')
  var mc_pregunta_5 = button.data('mc_pregunta_5')
  var mc_pregunta_6 = button.data('mc_pregunta_6')
  var mc_qec_neg = button.data('mc_qec_neg')
  var mc_qec_uf = button.data('mc_qec_uf')
  var mc_nota_final = button.data('mc_nota_final')
  var mc_descripcion_hallazgo = button.data('mc_descripcion_hallazgo')
  var mc_descripcion_plan_accion = button.data('mc_descripcion_plan_accion')
  var mc_fecha_cierre = button.data('mc_fecha_cierre')
  var mc_evaluador = button.data('mc_evaluador')
  var mc_evaluado = button.data('mc_evaluado')
  var mc_responsable = button.data('mc_responsable')
  var mc_cliente_nit = button.data('mc_cliente_nit')
  var mc_cliente_razon_social = button.data('mc_cliente_razon_social')
  var mc_usuario_de_red = button.data('mc_usuario_de_red')
  var mc_observacion_p1 = button.data('mc_observacion_p1')
  var mc_observacion_p2 = button.data('mc_observacion_p2')
  var mc_observacion_p3 = button.data('mc_observacion_p3')
  var mc_observacion_p4 = button.data('mc_observacion_p4')
  var mc_observacion_p5 = button.data('mc_observacion_p5')
  var mc_observacion_p6 = button.data('mc_observacion_p6')
  var mc_comentario_p1 = button.data('mc_comentario_p1')
  var mc_comentario_p2 = button.data('mc_comentario_p2')
  var mc_comentario_p3 = button.data('mc_comentario_p3')
  var mc_comentario_p4 = button.data('mc_comentario_p4')
  var mc_comentario_p5 = button.data('mc_comentario_p5')
  var mc_comentario_p6 = button.data('mc_comentario_p6')
  var modal = $(this)
  modal.find('.modal-body #mc_tipo_herramienta').val(mc_tipo_herramienta)
  modal.find('.modal-body #mc_fecha_monitoreo').val(mc_fecha_monitoreo)
  modal.find('.modal-body #mc_linea').val(mc_linea)
  modal.find('.modal-body #mc_fecha_correo').val(mc_fecha_correo)
  modal.find('.modal-body #mc_hora_correo').val(mc_hora_correo)
  modal.find('.modal-body #mc_requerimiento_cliente').val(mc_requerimiento_cliente)
  modal.find('.modal-body #mc_observaciones_monitoreo').val(mc_observaciones_monitoreo)
  modal.find('.modal-body #mc_id_scriba').val(mc_id_scriba)
  modal.find('.modal-body #mc_id_envio').val(mc_id_envio)
  modal.find('.modal-body #mc_pregunta_1').val(mc_pregunta_1)
  modal.find('.modal-body #mc_pregunta_2').val(mc_pregunta_2)
  modal.find('.modal-body #mc_pregunta_3').val(mc_pregunta_3)
  modal.find('.modal-body #mc_pregunta_4').val(mc_pregunta_4)
  modal.find('.modal-body #mc_pregunta_5').val(mc_pregunta_5)
  modal.find('.modal-body #mc_pregunta_6').val(mc_pregunta_6)
  modal.find('.modal-body #mc_qec_neg').val(mc_qec_neg)
  modal.find('.modal-body #mc_qec_uf').val(mc_qec_uf)
  modal.find('.modal-body #mc_nota_final').val(mc_nota_final)
  modal.find('.modal-body #mc_descripcion_hallazgo').val(mc_descripcion_hallazgo)
  modal.find('.modal-body #mc_descripcion_plan_accion').val(mc_descripcion_plan_accion)
  modal.find('.modal-body #mc_fecha_cierre').val(mc_fecha_cierre)
  modal.find('.modal-body #mc_evaluador').val(mc_evaluador)
  modal.find('.modal-body #mc_evaluado').val(mc_evaluado)
  modal.find('.modal-body #mc_responsable').val(mc_responsable)
  modal.find('.modal-body #mc_cliente_nit').val(mc_cliente_nit)
  modal.find('.modal-body #mc_cliente_razon_social').val(mc_cliente_razon_social)
  modal.find('.modal-body #mc_usuario_de_red').val(mc_usuario_de_red)
  modal.find('.modal-body #mc_observacion_p1').val(mc_observacion_p1)
  modal.find('.modal-body #mc_observacion_p2').val(mc_observacion_p2)
  modal.find('.modal-body #mc_observacion_p3').val(mc_observacion_p3)
  modal.find('.modal-body #mc_observacion_p4').val(mc_observacion_p4)
  modal.find('.modal-body #mc_observacion_p5').val(mc_observacion_p5)
  modal.find('.modal-body #mc_observacion_p6').val(mc_observacion_p6)
  modal.find('.modal-body #mc_comentario_p1').val(mc_comentario_p1)
  modal.find('.modal-body #mc_comentario_p2').val(mc_comentario_p2)
  modal.find('.modal-body #mc_comentario_p3').val(mc_comentario_p3)
  modal.find('.modal-body #mc_comentario_p4').val(mc_comentario_p4)
  modal.find('.modal-body #mc_comentario_p5').val(mc_comentario_p5)
  modal.find('.modal-body #mc_comentario_p6').val(mc_comentario_p6)
  $('.alert').hide();//Oculto alert
})











$('#dataViewVM').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Botón que activó el modal
  var ciudad = button.data('ciudad')
  var departamento = button.data('departamento') // Extraer la información de atributos de datos
  var tipo_ciudad = button.data('tipo_ciudad')
  var direccion = button.data('direccion')
  var nombre = button.data('nombre')
  var telefono = button.data('telefono')
  var lineaafectada = button.data('lineaafectada')
  var tiposervicio = button.data('tiposervicio')
  var tecnologia = button.data('tecnologia')
  var falla = button.data('falla')
  var permisoingreso = button.data('permisoingreso')
  var sigres = button.data('sigres')
  var modal = $(this)
  modal.find('.modal-body #departamento').text('• Departamento: '+departamento)
  modal.find('.modal-body #ciudad').text('• Ciudad: '+ciudad)
  modal.find('.modal-body #tipo_ciudad').text('• Tipo ciudad: '+tipo_ciudad)
  modal.find('.modal-body #direccion').text('• Dirección de la sede: '+direccion)
  modal.find('.modal-body #nombre').text('• Nombre del contacto: '+nombre)
  modal.find('.modal-body #telefono').text('• Número de contacto: '+telefono)
  modal.find('.modal-body #lineaafectada').text(lineaafectada)
  modal.find('.modal-body #tiposervicio').text('• Tipo de Servicio: '+tiposervicio)
  modal.find('.modal-body #tecnologia').text('• Tecnología UK: '+tecnologia)
  modal.find('.modal-body #falla').text('• Resumen Problema: '+falla)
  modal.find('.modal-body #permisoingreso').text('• Permisos de Ingreso: '+permisoingreso)
  modal.find('.modal-body #sigres').text(sigres)
  
  $('.alert').hide();//Oculto alert
})


$('#dataView_menu_servicios').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Botón que activó el modal
  var cliente = button.data('cliente') // Extraer la información de atributos de datos
  var modal = $(this)
  document.getElementById("vpnip").href = 'servicios_vpnip.php?pagina=0&id=null&cliente='+cliente;
  document.getElementById("ba").href = 'servicios_ba.php?pagina=0&id=null&cliente='+cliente;
  document.getElementById("lb").href = 'servicios_lb.php?pagina=0&id=null&cliente='+cliente;
  document.getElementById("pdti").href = 'servicios_pdti.php?pagina=0&id=null&cliente='+cliente;
  document.getElementById("tv").href = 'servicios_tv.php?pagina=0&id=null&cliente='+cliente;
  document.getElementById("e1").href = 'servicios_e1.php?pagina=0&id=null&cliente='+cliente;
  document.getElementById("pdv").href = 'servicios_pdv.php?pagina=0&id=null&cliente='+cliente;
  document.getElementById("tsip").href = 'servicios_tsip.php?pagina=0&id=null&cliente='+cliente;
  document.getElementById("est").href = 'servicios_estadisticas.php?cliente='+cliente;
  $('.alert').hide();//Oculto alert
})

$('#dataView_menu_servicios_crear').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Botón que activó el modal
  var cliente = button.data('cliente') // Extraer la información de atributos de datos
  var sede = button.data('sede') // Extraer la información de atributos de datos
  var modal = $(this)
  document.getElementById("vpnip").href = 'servicios_vpnip_crear.php?pagina=0&id=null&cliente='+cliente+'&sede='+sede;
  document.getElementById("ba").href = 'servicios_ba_crear.php?pagina=0&id=null&cliente='+cliente+'&sede='+sede;
  document.getElementById("lb").href = 'servicios_lb_crear.php?pagina=0&id=null&cliente='+cliente+'&sede='+sede;
  document.getElementById("pdti").href = 'servicios_pdti_crear.php?pagina=0&id=null&cliente='+cliente+'&sede='+sede;
  document.getElementById("tv").href = 'servicios_tv_crear.php?pagina=0&id=null&cliente='+cliente+'&sede='+sede;
  document.getElementById("e1").href = 'servicios_e1_crear.php?pagina=0&id=null&cliente='+cliente+'&sede='+sede;
  document.getElementById("pdv").href = 'servicios_pdv_crear.php?pagina=0&id=null&cliente='+cliente+'&sede='+sede;
  document.getElementById("tsip").href = 'servicios_tsip.php?pagina=0&id=null&cliente='+cliente;
  $('.alert').hide();//Oculto alert
})

$('#dataView_manual').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Botón que activó el modal
  var enlace = button.data('enlace') // Extraer la información de atributos de datos
  var titulo = button.data('titulo') // Extraer la información de atributos de datos
  var modal = $(this)
  document.getElementById("visor").src = enlace;
  modal.find('.modal-body #sub_titulo').text('► '+titulo)
  $('.alert').hide();//Oculto alert
})

$('#dataView_video').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Botón que activó el modal
  var enlace = button.data('enlace') // Extraer la información de atributos de datos
  var titulo = button.data('titulo') // Extraer la información de atributos de datos
  var modal = $(this)
  document.getElementById("visor_video").src = enlace;
  modal.find('.modal-body #sub_titulo_video').text('► '+titulo)
  $('.alert').hide();//Oculto alert
})

$('#modal_menu_servpnip').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Botón que activó el modal
  var cliente = button.data('cliente') // Extraer la información de atributos de datos
  var sede = button.data('sede') // Extraer la información de atributos de datos
  var nodo = button.data('nodo') // Extraer la información de atributos de datos
  var sap = button.data('sap') // Extraer la información de atributos de datos
  var servicio = button.data('servicio') // Extraer la información de atributos de datos
  var modal = $(this)
  document.getElementById("qos").href = 'servicios_vpnip_qos_crear.php?cliente='+cliente+'&servicio='+servicio;
  document.getElementById("tercero").href = 'servicios_vpnip_tercero_crear.php?cliente='+cliente+'&servicio='+servicio;
  document.getElementById("ot").href = 'servicios_vpnip_ot_crear.php?cliente='+cliente+'&servicio='+servicio;
  document.getElementById("topologia_wan").href = 'servicios_vpnip_topologiawan_crear.php?cliente='+cliente+'&servicio='+servicio+'&sede='+sede;
  document.getElementById("topologia_lan").href = 'servicios_vpnip_topologialan_crear.php?cliente='+cliente+'&servicio='+servicio+'&sede='+sede;
  document.getElementById("plantillas").href = 'servicios_vpnip_plantilla_crear.php?cliente='+cliente+'&servicio='+servicio+'&sede='+sede+'&plantilla=null';
  document.getElementById("observaciones_vpnip").href = 'servicios_vpnip_observaciones_crear.php?cliente='+cliente+'&servicio='+servicio;
  document.getElementById("admin_lan").href = 'servicios_vpnip_admin_lan_crear.php?cliente='+cliente+'&servicio='+servicio;
  
  $('.alert').hide();//Oculto alert
})

$('#dataView_nodos_mpls').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Botón que activó el modal
  var nombre = button.data('nombre') // Extraer la información de atributos de datos
  var ip = button.data('ip')
  var tipo_nodo = button.data('tipo_nodo')
  var plataforma = button.data('plataforma')
  var tipo_equipo = button.data('tipo_equipo')
  var ciudad = button.data('ciudad')
  var direccion = button.data('direccion')
  var latitud = button.data('latitud')
  var longitud = button.data('longitud')
  var last_update = button.data('last_update')
  var modal = $(this)
  modal.find('.modal-body #nombre').val(nombre)
  modal.find('.modal-body #ip').val(ip)
  modal.find('.modal-body #tipo_nodo').val(tipo_nodo)
  modal.find('.modal-body #plataforma').val(plataforma)
  modal.find('.modal-body #tipo_equipo').val(tipo_equipo)
  modal.find('.modal-body #ciudad').val(ciudad)
  modal.find('.modal-body #direccion').val(direccion)
  modal.find('.modal-body #latitud').val(latitud)
  modal.find('.modal-body #longitud').val(longitud)
  modal.find('.modal-body #last_update').val(last_update)
  
  $('.alert').hide();//Oculto alert
})

$('#dataView_sedes').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Botón que activó el modal
  var nombre_sede = button.data('nombre_sede') // Extraer la información de atributos de datos
  var horario = button.data('horario')
  var direccion = button.data('direccion')
  var ciudad = button.data('ciudad')
  var tipo_ciudad = button.data('tipo_ciudad')
  var contratista = button.data('contratista')
  var desplazamiento = button.data('desplazamiento')
  var observaciones_sede = button.data('observaciones_sede')
  var last_update = button.data('last_update')
  var c1_nombre_1 = button.data('c1_nombre_1')
  var c1_telefono_1 = button.data('c1_telefono_1')
  var c1_telefono_2 = button.data('c1_telefono_2')
  var c1_tipo = button.data('c1_tipo')
  var c1_correo = button.data('c1_correo')
  var c1_cargo = button.data('c1_cargo')
  var c1_last_update = button.data('c1_last_update')
  var c1_observaciones = button.data('c1_observaciones')
  var c2_nombre_1 = button.data('c2_nombre_1')
  var c2_telefono_1 = button.data('c2_telefono_1')
  var c2_telefono_2 = button.data('c2_telefono_2')
  var c2_tipo = button.data('c2_tipo')
  var c2_correo = button.data('c2_correo')
  var c2_cargo = button.data('c2_cargo')
  var c2_last_update = button.data('c2_last_update')
  var c2_observaciones = button.data('c2_observaciones')
  var nit = button.data('nit')
  var razon_social = button.data('razon_social')
  var atencion = button.data('atencion')
  var segmento = button.data('segmento')
  var cluster = button.data('cluster')
  var cnoc = button.data('cnoc')
  var cgp = button.data('cgp')
  var observaciones = button.data('observaciones')
  var modal = $(this)
  modal.find('.modal-body #nombre_sede').val(nombre_sede)
  modal.find('.modal-body #horario').val(horario)
  modal.find('.modal-body #direccion').val(direccion)
  modal.find('.modal-body #ciudad').val(ciudad)
  modal.find('.modal-body #tipo_ciudad').val(tipo_ciudad)
  modal.find('.modal-body #contratista').val(contratista)
  modal.find('.modal-body #desplazamiento').val(desplazamiento)
  modal.find('.modal-body #observaciones_sede').val(observaciones_sede)
  modal.find('.modal-body #last_update').val(last_update)
  modal.find('.modal-body #c1_nombre_1').val(c1_nombre_1)
  modal.find('.modal-body #c1_telefono_1').val(c1_telefono_1)
  modal.find('.modal-body #c1_telefono_2').val(c1_telefono_2)
  modal.find('.modal-body #c1_tipo').val(c1_tipo)
  modal.find('.modal-body #c1_correo').val(c1_correo)
  modal.find('.modal-body #c1_cargo').val(c1_cargo)
  modal.find('.modal-body #c1_last_update').val(c1_last_update)
  modal.find('.modal-body #c1_observaciones').val(c1_observaciones)
  modal.find('.modal-body #c2_nombre_1').val(c2_nombre_1)
  modal.find('.modal-body #c2_telefono_1').val(c2_telefono_1)
  modal.find('.modal-body #c2_telefono_2').val(c2_telefono_2)
  modal.find('.modal-body #c2_tipo').val(c2_tipo)
  modal.find('.modal-body #c2_correo').val(c2_correo)
  modal.find('.modal-body #c2_cargo').val(c2_cargo)
  modal.find('.modal-body #c2_last_update').val(c2_last_update)
  modal.find('.modal-body #c2_observaciones').val(c2_observaciones)
  modal.find('.modal-body #nit').val(nit)
  modal.find('.modal-body #razon_social').val(razon_social)
  modal.find('.modal-body #atencion').val(atencion)
  modal.find('.modal-body #segmento').val(segmento)
  modal.find('.modal-body #cluster').val(cluster)
  modal.find('.modal-body #cnoc').val(cnoc)
  modal.find('.modal-body #cgp').val(cgp)
  modal.find('.modal-body #observaciones').val(observaciones)
  $('.alert').hide();//Oculto alert
})


$('#dataView_vpnip').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Botón que activó el modal
  var ds_servicio = button.data('ds_servicio') // Extraer la información de atributos de datos
  var ds_facturacion = button.data('ds_facturacion')
  var tipo_servicio = button.data('tipo_servicio')
  var estado_servicio = button.data('estado_servicio')
  var criticidad = button.data('criticidad')
  var fecha_alta = button.data('fecha_alta')
  var fecha_baja = button.data('fecha_baja')
  var ans = button.data('ans')
  var tipo_enlace = button.data('tipo_enlace')
  var bw = button.data('bw')
  var vprn = button.data('vprn')
  var pe = button.data('pe')
  var vrf = button.data('vrf')
  var interface = button.data('interface')
  var ip_interface = button.data('ip_interface')
  var sap = button.data('sap')
  var enrutamiento = button.data('enrutamiento')
  var wan = button.data('wan')
  var lan = button.data('lan')
  var loopback = button.data('loopback')
  var propiedad = button.data('propiedad')
  var marca = button.data('marca')
  var modelo = button.data('modelo')
  var serial = button.data('serial')
  var id_tx = button.data('id_tx')
  var propiedad_uk = button.data('propiedad_uk')
  var medio_uk = button.data('medio_uk')
  var distrito = button.data('distrito')
  var anillo = button.data('anillo')
  var nds = button.data('nds')
  var nombre_dslam = button.data('nombre_dslam')
  var ip_dslam = button.data('ip_dslam')
  var puerto_dslam = button.data('puerto_dslam')
  var nombre_switch = button.data('nombre_switch')
  var ip_switch = button.data('ip_switch')
  var puerto_switch = button.data('puerto_switch')
  var topologia_formato = button.data('topologia_formato')
  var exclusion_topologia = button.data('exclusion_topologia')
  var exclusion_plantilla = button.data('exclusion_plantilla')
  var nodo = button.data('nodo')
  var servicio_actualizacion = button.data('servicio_actualizacion')
  var sede = button.data('sede')
  var horario = button.data('horario')
  var direccion = button.data('direccion')
  var ciudad = button.data('ciudad')
  var tipo_ciudad = button.data('tipo_ciudad')
  var contratista = button.data('contratista')
  var desplazamiento = button.data('desplazamiento')
  var sede_observaciones = button.data('sede_observaciones')
  var sede_actualizacion = button.data('sede_actualizacion')
  var c1_nombre_1 = button.data('c1_nombre_1')
  var c1_telefono_1 = button.data('c1_telefono_1')
  var c1_telefono_2 = button.data('c1_telefono_2')
  var c1_tipo = button.data('c1_tipo')
  var c1_correo = button.data('c1_correo')
  var c1_cargo = button.data('c1_cargo')
  var c1_last_update = button.data('c1_last_update')
  var c1_observaciones = button.data('c1_observaciones')
  var c2_nombre_1 = button.data('c2_nombre_1')
  var c2_telefono_1 = button.data('c2_telefono_1')
  var c2_telefono_2 = button.data('c2_telefono_2')
  var c2_tipo = button.data('c2_tipo')
  var c2_correo = button.data('c2_correo')
  var c2_cargo = button.data('c2_cargo')
  var c2_last_update = button.data('c2_last_update')
  var c2_observaciones = button.data('c2_observaciones')
  var nit = button.data('nit')
  var razon_social = button.data('razon_social')
  var atencion = button.data('atencion')
  var segmento = button.data('segmento')
  var cluster = button.data('cluster')
  var cnoc = button.data('cnoc')
  var cgp = button.data('cgp')
  var observaciones = button.data('observaciones')
  var modal = $(this)
  modal.find('.modal-body #ds_servicio').val(ds_servicio)
  modal.find('.modal-body #ds_facturacion').val(ds_facturacion)
  modal.find('.modal-body #tipo_servicio').val(tipo_servicio)
  modal.find('.modal-body #estado_servicio').val(estado_servicio)
  modal.find('.modal-body #criticidad').val(criticidad)
  modal.find('.modal-body #fecha_alta').val(fecha_alta)
  modal.find('.modal-body #fecha_baja').val(fecha_baja)
  modal.find('.modal-body #ans').val(ans)
  modal.find('.modal-body #tipo_enlace').val(tipo_enlace)
  modal.find('.modal-body #bw').val(bw)
  modal.find('.modal-body #vprn').val(vprn)
  modal.find('.modal-body #pe').val(pe)
  modal.find('.modal-body #vrf').val(vrf)
  modal.find('.modal-body #interface').val(interface)
  modal.find('.modal-body #ip_interface').val(ip_interface)
  modal.find('.modal-body #sap').val(sap)
  modal.find('.modal-body #enrutamiento').val(enrutamiento)
  modal.find('.modal-body #wan').val(wan)
  modal.find('.modal-body #lan').val(lan)
  modal.find('.modal-body #loopback').val(loopback)
  modal.find('.modal-body #propiedad').val(propiedad)
  modal.find('.modal-body #marca').val(marca)
  modal.find('.modal-body #modelo').val(modelo)
  modal.find('.modal-body #serial').val(serial)
  modal.find('.modal-body #id_tx').val(id_tx)
  modal.find('.modal-body #propiedad_uk').val(propiedad_uk)
  modal.find('.modal-body #medio_uk').val(medio_uk)
  modal.find('.modal-body #distrito').val(distrito)
  modal.find('.modal-body #anillo').val(anillo)
  modal.find('.modal-body #nds').val(nds)
  modal.find('.modal-body #nombre_dslam').val(nombre_dslam)
  modal.find('.modal-body #ip_dslam').val(ip_dslam)
  modal.find('.modal-body #puerto_dslam').val(puerto_dslam)
  modal.find('.modal-body #nombre_switch').val(nombre_switch)
  modal.find('.modal-body #ip_switch').val(ip_switch)
  modal.find('.modal-body #puerto_switch').val(puerto_switch)
  modal.find('.modal-body #topologia_formato').val(topologia_formato)
  modal.find('.modal-body #exclusion_topologia').val(exclusion_topologia)
  modal.find('.modal-body #exclusion_plantilla').val(exclusion_plantilla)
  modal.find('.modal-body #nodo').val(nodo)
  modal.find('.modal-body #servicio_actualizacion').val(servicio_actualizacion)
  modal.find('.modal-body #sede').val(sede)
  modal.find('.modal-body #horario').val(horario)
  modal.find('.modal-body #direccion').val(direccion)
  modal.find('.modal-body #ciudad').val(ciudad)
  modal.find('.modal-body #tipo_ciudad').val(tipo_ciudad)
  modal.find('.modal-body #contratista').val(contratista)
  modal.find('.modal-body #desplazamiento').val(desplazamiento)
  modal.find('.modal-body #sede_observaciones').val(sede_observaciones)
  modal.find('.modal-body #sede_actualizacion').val(sede_actualizacion)
  modal.find('.modal-body #c1_nombre_1').val(c1_nombre_1)
  modal.find('.modal-body #c1_telefono_1').val(c1_telefono_1)
  modal.find('.modal-body #c1_telefono_2').val(c1_telefono_2)
  modal.find('.modal-body #c1_tipo').val(c1_tipo)
  modal.find('.modal-body #c1_correo').val(c1_correo)
  modal.find('.modal-body #c1_cargo').val(c1_cargo)
  modal.find('.modal-body #c1_last_update').val(c1_last_update)
  modal.find('.modal-body #c1_observaciones').val(c1_observaciones)
  modal.find('.modal-body #c2_nombre_1').val(c2_nombre_1)
  modal.find('.modal-body #c2_telefono_1').val(c2_telefono_1)
  modal.find('.modal-body #c2_telefono_2').val(c2_telefono_2)
  modal.find('.modal-body #c2_tipo').val(c2_tipo)
  modal.find('.modal-body #c2_correo').val(c2_correo)
  modal.find('.modal-body #c2_cargo').val(c2_cargo)
  modal.find('.modal-body #c2_last_update').val(c2_last_update)
  modal.find('.modal-body #c2_observaciones').val(c2_observaciones)
  modal.find('.modal-body #nit').val(nit)
  modal.find('.modal-body #razon_social').val(razon_social)
  modal.find('.modal-body #atencion').val(atencion)
  modal.find('.modal-body #segmento').val(segmento)
  modal.find('.modal-body #cluster').val(cluster)
  modal.find('.modal-body #cnoc').val(cnoc)
  modal.find('.modal-body #cgp').val(cgp)
  modal.find('.modal-body #observaciones').val(observaciones)
  $('.alert').hide();//Oculto alert
})

$('#dataView_lb').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Botón que activó el modal
  var num_abonado = button.data('num_abonado') // Extraer la información de atributos de datos
  var estado_servicio = button.data('estado_servicio')
  var criticidad = button.data('criticidad')
  var fecha_alta = button.data('fecha_alta')
  var fecha_baja = button.data('fecha_baja')
  var tipo_servicio = button.data('tipo_servicio')
  var central = button.data('central')
  var zona = button.data('zona')
  var servicio_observaciones = button.data('servicio_observaciones')
  var servicio_actualizacion = button.data('servicio_actualizacion')
  var sede = button.data('sede')
  var horario = button.data('horario')
  var direccion = button.data('direccion')
  var ciudad = button.data('ciudad')
  var tipo_ciudad = button.data('tipo_ciudad')
  var contratista = button.data('contratista')
  var desplazamiento = button.data('desplazamiento')
  var sede_observaciones = button.data('sede_observaciones')
  var sede_actualizacion = button.data('sede_actualizacion')
  var c1_nombre_1 = button.data('c1_nombre_1')
  var c1_telefono_1 = button.data('c1_telefono_1')
  var c1_telefono_2 = button.data('c1_telefono_2')
  var c1_tipo = button.data('c1_tipo')
  var c1_correo = button.data('c1_correo')
  var c1_cargo = button.data('c1_cargo')
  var c1_last_update = button.data('c1_last_update')
  var c1_observaciones = button.data('c1_observaciones')
  var c2_nombre_1 = button.data('c2_nombre_1')
  var c2_telefono_1 = button.data('c2_telefono_1')
  var c2_telefono_2 = button.data('c2_telefono_2')
  var c2_tipo = button.data('c2_tipo')
  var c2_correo = button.data('c2_correo')
  var c2_cargo = button.data('c2_cargo')
  var c2_last_update = button.data('c2_last_update')
  var c2_observaciones = button.data('c2_observaciones')
  var nit = button.data('nit')
  var razon_social = button.data('razon_social')
  var atencion = button.data('atencion')
  var segmento = button.data('segmento')
  var cluster = button.data('cluster')
  var cnoc = button.data('cnoc')
  var cgp = button.data('cgp')
  var observaciones = button.data('observaciones')
  var modal = $(this)
  modal.find('.modal-body #num_abonado').val(num_abonado)
  modal.find('.modal-body #estado_servicio').val(estado_servicio)
  modal.find('.modal-body #criticidad').val(criticidad)
  modal.find('.modal-body #fecha_alta').val(fecha_alta)
  modal.find('.modal-body #fecha_baja').val(fecha_baja)
  modal.find('.modal-body #central').val(central)
  modal.find('.modal-body #zona').val(zona)
  modal.find('.modal-body #servicio_observaciones').val(servicio_observaciones)
  modal.find('.modal-body #servicio_actualizacion').val(servicio_actualizacion)
  modal.find('.modal-body #sede').val(sede)
  modal.find('.modal-body #horario').val(horario)
  modal.find('.modal-body #direccion').val(direccion)
  modal.find('.modal-body #ciudad').val(ciudad)
  modal.find('.modal-body #tipo_ciudad').val(tipo_ciudad)
  modal.find('.modal-body #contratista').val(contratista)
  modal.find('.modal-body #desplazamiento').val(desplazamiento)
  modal.find('.modal-body #sede_observaciones').val(sede_observaciones)
  modal.find('.modal-body #sede_actualizacion').val(sede_actualizacion)
  modal.find('.modal-body #c1_nombre_1').val(c1_nombre_1)
  modal.find('.modal-body #c1_telefono_1').val(c1_telefono_1)
  modal.find('.modal-body #c1_telefono_2').val(c1_telefono_2)
  modal.find('.modal-body #c1_tipo').val(c1_tipo)
  modal.find('.modal-body #c1_correo').val(c1_correo)
  modal.find('.modal-body #c1_cargo').val(c1_cargo)
  modal.find('.modal-body #c1_last_update').val(c1_last_update)
  modal.find('.modal-body #c1_observaciones').val(c1_observaciones)
  modal.find('.modal-body #c2_nombre_1').val(c2_nombre_1)
  modal.find('.modal-body #c2_telefono_1').val(c2_telefono_1)
  modal.find('.modal-body #c2_telefono_2').val(c2_telefono_2)
  modal.find('.modal-body #c2_tipo').val(c2_tipo)
  modal.find('.modal-body #c2_correo').val(c2_correo)
  modal.find('.modal-body #c2_cargo').val(c2_cargo)
  modal.find('.modal-body #c2_last_update').val(c2_last_update)
  modal.find('.modal-body #c2_observaciones').val(c2_observaciones)
  modal.find('.modal-body #nit').val(nit)
  modal.find('.modal-body #razon_social').val(razon_social)
  modal.find('.modal-body #atencion').val(atencion)
  modal.find('.modal-body #segmento').val(segmento)
  modal.find('.modal-body #cluster').val(cluster)
  modal.find('.modal-body #cnoc').val(cnoc)
  modal.find('.modal-body #cgp').val(cgp)
  modal.find('.modal-body #observaciones').val(observaciones)
  $('.alert').hide();//Oculto alert
})

$('#dataView_pdti').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Botón que activó el modal
  var serial = button.data('serial') // Extraer la información de atributos de datos
  var estado_servicio = button.data('estado_servicio')
  var criticidad = button.data('criticidad')
  var fecha_alta = button.data('fecha_alta')
  var fecha_baja = button.data('fecha_baja')
  var tipo_servicio = button.data('tipo_servicio')
  var tipo_equipo = button.data('tipo_equipo')
  var sistema_operativo = button.data('sistema_operativo')
  var inicio_garantia = button.data('inicio_garantia')
  var fin_garantia = button.data('fin_garantia')
  var servicio_observaciones = button.data('servicio_observaciones')
  var servicio_actualizacion = button.data('servicio_actualizacion')
  var sede = button.data('sede')
  var horario = button.data('horario')
  var direccion = button.data('direccion')
  var ciudad = button.data('ciudad')
  var tipo_ciudad = button.data('tipo_ciudad')
  var contratista = button.data('contratista')
  var desplazamiento = button.data('desplazamiento')
  var sede_observaciones = button.data('sede_observaciones')
  var sede_actualizacion = button.data('sede_actualizacion')
  var c1_nombre_1 = button.data('c1_nombre_1')
  var c1_telefono_1 = button.data('c1_telefono_1')
  var c1_telefono_2 = button.data('c1_telefono_2')
  var c1_tipo = button.data('c1_tipo')
  var c1_correo = button.data('c1_correo')
  var c1_cargo = button.data('c1_cargo')
  var c1_last_update = button.data('c1_last_update')
  var c1_observaciones = button.data('c1_observaciones')
  var c2_nombre_1 = button.data('c2_nombre_1')
  var c2_telefono_1 = button.data('c2_telefono_1')
  var c2_telefono_2 = button.data('c2_telefono_2')
  var c2_tipo = button.data('c2_tipo')
  var c2_correo = button.data('c2_correo')
  var c2_cargo = button.data('c2_cargo')
  var c2_last_update = button.data('c2_last_update')
  var c2_observaciones = button.data('c2_observaciones')
  var nit = button.data('nit')
  var razon_social = button.data('razon_social')
  var atencion = button.data('atencion')
  var segmento = button.data('segmento')
  var cluster = button.data('cluster')
  var cnoc = button.data('cnoc')
  var cgp = button.data('cgp')
  var observaciones = button.data('observaciones')
  var modal = $(this)
  modal.find('.modal-body #serial').val(serial)
  modal.find('.modal-body #estado_servicio').val(estado_servicio)
  modal.find('.modal-body #criticidad').val(criticidad)
  modal.find('.modal-body #fecha_alta').val(fecha_alta)
  modal.find('.modal-body #fecha_baja').val(fecha_baja)
  modal.find('.modal-body #tipo_equipo').val(tipo_equipo)
  modal.find('.modal-body #sistema_operativo').val(sistema_operativo)
  modal.find('.modal-body #inicio_garantia').val(inicio_garantia)
  modal.find('.modal-body #fin_garantia').val(fin_garantia)
  modal.find('.modal-body #servicio_observaciones').val(servicio_observaciones)
  modal.find('.modal-body #servicio_actualizacion').val(servicio_actualizacion)
  modal.find('.modal-body #sede').val(sede)
  modal.find('.modal-body #horario').val(horario)
  modal.find('.modal-body #direccion').val(direccion)
  modal.find('.modal-body #ciudad').val(ciudad)
  modal.find('.modal-body #tipo_ciudad').val(tipo_ciudad)
  modal.find('.modal-body #contratista').val(contratista)
  modal.find('.modal-body #desplazamiento').val(desplazamiento)
  modal.find('.modal-body #sede_observaciones').val(sede_observaciones)
  modal.find('.modal-body #sede_actualizacion').val(sede_actualizacion)
  modal.find('.modal-body #c1_nombre_1').val(c1_nombre_1)
  modal.find('.modal-body #c1_telefono_1').val(c1_telefono_1)
  modal.find('.modal-body #c1_telefono_2').val(c1_telefono_2)
  modal.find('.modal-body #c1_tipo').val(c1_tipo)
  modal.find('.modal-body #c1_correo').val(c1_correo)
  modal.find('.modal-body #c1_cargo').val(c1_cargo)
  modal.find('.modal-body #c1_last_update').val(c1_last_update)
  modal.find('.modal-body #c1_observaciones').val(c1_observaciones)
  modal.find('.modal-body #c2_nombre_1').val(c2_nombre_1)
  modal.find('.modal-body #c2_telefono_1').val(c2_telefono_1)
  modal.find('.modal-body #c2_telefono_2').val(c2_telefono_2)
  modal.find('.modal-body #c2_tipo').val(c2_tipo)
  modal.find('.modal-body #c2_correo').val(c2_correo)
  modal.find('.modal-body #c2_cargo').val(c2_cargo)
  modal.find('.modal-body #c2_last_update').val(c2_last_update)
  modal.find('.modal-body #c2_observaciones').val(c2_observaciones)
  modal.find('.modal-body #nit').val(nit)
  modal.find('.modal-body #razon_social').val(razon_social)
  modal.find('.modal-body #atencion').val(atencion)
  modal.find('.modal-body #segmento').val(segmento)
  modal.find('.modal-body #cluster').val(cluster)
  modal.find('.modal-body #cnoc').val(cnoc)
  modal.find('.modal-body #cgp').val(cgp)
  modal.find('.modal-body #observaciones').val(observaciones)
  $('.alert').hide();//Oculto alert
})

$('#dataView_tv').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Botón que activó el modal
  var serial = button.data('serial') // Extraer la información de atributos de datos
  var estado_servicio = button.data('estado_servicio')
  var criticidad = button.data('criticidad')
  var fecha_alta = button.data('fecha_alta')
  var fecha_baja = button.data('fecha_baja')
  var tipo_servicio = button.data('tipo_servicio')
  var tipo_senal = button.data('tipo_senal')
  var tipo_escalamiento = button.data('tipo_escalamiento')
  var marca_deco = button.data('marca_deco')
  var servicio_observaciones = button.data('servicio_observaciones')
  var servicio_actualizacion = button.data('servicio_actualizacion')
  var sede = button.data('sede')
  var horario = button.data('horario')
  var direccion = button.data('direccion')
  var ciudad = button.data('ciudad')
  var tipo_ciudad = button.data('tipo_ciudad')
  var contratista = button.data('contratista')
  var desplazamiento = button.data('desplazamiento')
  var sede_observaciones = button.data('sede_observaciones')
  var sede_actualizacion = button.data('sede_actualizacion')
  var c1_nombre_1 = button.data('c1_nombre_1')
  var c1_telefono_1 = button.data('c1_telefono_1')
  var c1_telefono_2 = button.data('c1_telefono_2')
  var c1_tipo = button.data('c1_tipo')
  var c1_correo = button.data('c1_correo')
  var c1_cargo = button.data('c1_cargo')
  var c1_last_update = button.data('c1_last_update')
  var c1_observaciones = button.data('c1_observaciones')
  var c2_nombre_1 = button.data('c2_nombre_1')
  var c2_telefono_1 = button.data('c2_telefono_1')
  var c2_telefono_2 = button.data('c2_telefono_2')
  var c2_tipo = button.data('c2_tipo')
  var c2_correo = button.data('c2_correo')
  var c2_cargo = button.data('c2_cargo')
  var c2_last_update = button.data('c2_last_update')
  var c2_observaciones = button.data('c2_observaciones')
  var nit = button.data('nit')
  var razon_social = button.data('razon_social')
  var atencion = button.data('atencion')
  var segmento = button.data('segmento')
  var cluster = button.data('cluster')
  var cnoc = button.data('cnoc')
  var cgp = button.data('cgp')
  var observaciones = button.data('observaciones')
  var modal = $(this)
  modal.find('.modal-body #serial').val(serial)
  modal.find('.modal-body #estado_servicio').val(estado_servicio)
  modal.find('.modal-body #criticidad').val(criticidad)
  modal.find('.modal-body #fecha_alta').val(fecha_alta)
  modal.find('.modal-body #fecha_baja').val(fecha_baja)
  modal.find('.modal-body #tipo_senal').val(tipo_senal)
  modal.find('.modal-body #tipo_escalamiento').val(tipo_escalamiento)
  modal.find('.modal-body #marca_deco').val(marca_deco)
  modal.find('.modal-body #servicio_observaciones').val(servicio_observaciones)
  modal.find('.modal-body #servicio_actualizacion').val(servicio_actualizacion)
  modal.find('.modal-body #sede').val(sede)
  modal.find('.modal-body #horario').val(horario)
  modal.find('.modal-body #direccion').val(direccion)
  modal.find('.modal-body #ciudad').val(ciudad)
  modal.find('.modal-body #tipo_ciudad').val(tipo_ciudad)
  modal.find('.modal-body #contratista').val(contratista)
  modal.find('.modal-body #desplazamiento').val(desplazamiento)
  modal.find('.modal-body #sede_observaciones').val(sede_observaciones)
  modal.find('.modal-body #sede_actualizacion').val(sede_actualizacion)
  modal.find('.modal-body #c1_nombre_1').val(c1_nombre_1)
  modal.find('.modal-body #c1_telefono_1').val(c1_telefono_1)
  modal.find('.modal-body #c1_telefono_2').val(c1_telefono_2)
  modal.find('.modal-body #c1_tipo').val(c1_tipo)
  modal.find('.modal-body #c1_correo').val(c1_correo)
  modal.find('.modal-body #c1_cargo').val(c1_cargo)
  modal.find('.modal-body #c1_last_update').val(c1_last_update)
  modal.find('.modal-body #c1_observaciones').val(c1_observaciones)
  modal.find('.modal-body #c2_nombre_1').val(c2_nombre_1)
  modal.find('.modal-body #c2_telefono_1').val(c2_telefono_1)
  modal.find('.modal-body #c2_telefono_2').val(c2_telefono_2)
  modal.find('.modal-body #c2_tipo').val(c2_tipo)
  modal.find('.modal-body #c2_correo').val(c2_correo)
  modal.find('.modal-body #c2_cargo').val(c2_cargo)
  modal.find('.modal-body #c2_last_update').val(c2_last_update)
  modal.find('.modal-body #c2_observaciones').val(c2_observaciones)
  modal.find('.modal-body #nit').val(nit)
  modal.find('.modal-body #razon_social').val(razon_social)
  modal.find('.modal-body #atencion').val(atencion)
  modal.find('.modal-body #segmento').val(segmento)
  modal.find('.modal-body #cluster').val(cluster)
  modal.find('.modal-body #cnoc').val(cnoc)
  modal.find('.modal-body #cgp').val(cgp)
  modal.find('.modal-body #observaciones').val(observaciones)
  $('.alert').hide();//Oculto alert
})

$('#dataView_pdv').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Botón que activó el modal
  var piloto = button.data('piloto') // Extraer la información de atributos de datos
  var estado_servicio = button.data('estado_servicio')
  var criticidad = button.data('criticidad')
  var fecha_alta = button.data('fecha_alta')
  var fecha_baja = button.data('fecha_baja')
  var tipo_servicio = button.data('tipo_servicio')
  var proveedor = button.data('proveedor')
  var marca_planta = button.data('marca_planta')
  var servicio_observaciones = button.data('servicio_observaciones')
  var servicio_actualizacion = button.data('servicio_actualizacion')
  var sede = button.data('sede')
  var horario = button.data('horario')
  var direccion = button.data('direccion')
  var ciudad = button.data('ciudad')
  var tipo_ciudad = button.data('tipo_ciudad')
  var contratista = button.data('contratista')
  var desplazamiento = button.data('desplazamiento')
  var sede_observaciones = button.data('sede_observaciones')
  var sede_actualizacion = button.data('sede_actualizacion')
  var c1_nombre_1 = button.data('c1_nombre_1')
  var c1_telefono_1 = button.data('c1_telefono_1')
  var c1_telefono_2 = button.data('c1_telefono_2')
  var c1_tipo = button.data('c1_tipo')
  var c1_correo = button.data('c1_correo')
  var c1_cargo = button.data('c1_cargo')
  var c1_last_update = button.data('c1_last_update')
  var c1_observaciones = button.data('c1_observaciones')
  var c2_nombre_1 = button.data('c2_nombre_1')
  var c2_telefono_1 = button.data('c2_telefono_1')
  var c2_telefono_2 = button.data('c2_telefono_2')
  var c2_tipo = button.data('c2_tipo')
  var c2_correo = button.data('c2_correo')
  var c2_cargo = button.data('c2_cargo')
  var c2_last_update = button.data('c2_last_update')
  var c2_observaciones = button.data('c2_observaciones')
  var nit = button.data('nit')
  var razon_social = button.data('razon_social')
  var atencion = button.data('atencion')
  var segmento = button.data('segmento')
  var cluster = button.data('cluster')
  var cnoc = button.data('cnoc')
  var cgp = button.data('cgp')
  var observaciones = button.data('observaciones')
  var modal = $(this)
  modal.find('.modal-body #piloto').val(piloto)
  modal.find('.modal-body #estado_servicio').val(estado_servicio)
  modal.find('.modal-body #criticidad').val(criticidad)
  modal.find('.modal-body #fecha_alta').val(fecha_alta)
  modal.find('.modal-body #fecha_baja').val(fecha_baja)
  modal.find('.modal-body #proveedor').val(proveedor)
  modal.find('.modal-body #marca_planta').val(marca_planta)
  modal.find('.modal-body #servicio_observaciones').val(servicio_observaciones)
  modal.find('.modal-body #servicio_actualizacion').val(servicio_actualizacion)
  modal.find('.modal-body #sede').val(sede)
  modal.find('.modal-body #horario').val(horario)
  modal.find('.modal-body #direccion').val(direccion)
  modal.find('.modal-body #ciudad').val(ciudad)
  modal.find('.modal-body #tipo_ciudad').val(tipo_ciudad)
  modal.find('.modal-body #contratista').val(contratista)
  modal.find('.modal-body #desplazamiento').val(desplazamiento)
  modal.find('.modal-body #sede_observaciones').val(sede_observaciones)
  modal.find('.modal-body #sede_actualizacion').val(sede_actualizacion)
  modal.find('.modal-body #c1_nombre_1').val(c1_nombre_1)
  modal.find('.modal-body #c1_telefono_1').val(c1_telefono_1)
  modal.find('.modal-body #c1_telefono_2').val(c1_telefono_2)
  modal.find('.modal-body #c1_tipo').val(c1_tipo)
  modal.find('.modal-body #c1_correo').val(c1_correo)
  modal.find('.modal-body #c1_cargo').val(c1_cargo)
  modal.find('.modal-body #c1_last_update').val(c1_last_update)
  modal.find('.modal-body #c1_observaciones').val(c1_observaciones)
  modal.find('.modal-body #c2_nombre_1').val(c2_nombre_1)
  modal.find('.modal-body #c2_telefono_1').val(c2_telefono_1)
  modal.find('.modal-body #c2_telefono_2').val(c2_telefono_2)
  modal.find('.modal-body #c2_tipo').val(c2_tipo)
  modal.find('.modal-body #c2_correo').val(c2_correo)
  modal.find('.modal-body #c2_cargo').val(c2_cargo)
  modal.find('.modal-body #c2_last_update').val(c2_last_update)
  modal.find('.modal-body #c2_observaciones').val(c2_observaciones)
  modal.find('.modal-body #nit').val(nit)
  modal.find('.modal-body #razon_social').val(razon_social)
  modal.find('.modal-body #atencion').val(atencion)
  modal.find('.modal-body #segmento').val(segmento)
  modal.find('.modal-body #cluster').val(cluster)
  modal.find('.modal-body #cnoc').val(cnoc)
  modal.find('.modal-body #cgp').val(cgp)
  modal.find('.modal-body #observaciones').val(observaciones)
  $('.alert').hide();//Oculto alert
})

$('#dataView_ba').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Botón que activó el modal
  var ds_servicio = button.data('ds_servicio') // Extraer la información de atributos de datos
  var tipo_servicio = button.data('tipo_servicio')
  var abonado = button.data('abonado')
  var estado_servicio = button.data('estado_servicio')
  var criticidad = button.data('criticidad')
  var fecha_alta = button.data('fecha_alta')
  var fecha_baja = button.data('fecha_baja')
  var ans = button.data('ans')
  var bw = button.data('bw')
  var nombre_dslam = button.data('nombre_dslam')
  var ip_dslam = button.data('ip_dslam')
  var cta_padre = button.data('cta_padre')
  var dir_tipo = button.data('dir_tipo')
  var pool_ip = button.data('pool_ip')
  var pot = button.data('pot')
  var pto_adsl = button.data('pto_adsl')
  var tecnologia = button.data('tecnologia')
  var nombre_nisip = button.data('nombre_nisip')
  var ip_nisip = button.data('ip_nisip')
  var vlan_nisip = button.data('vlan_nisip')
  var vrf_nisip = button.data('vrf_nisip')
  var medio = button.data('medio')
  var marca_modem = button.data('marca_modem')
  var modelo_modem = button.data('modelo_modem')
  var serial_modem = button.data('serial_modem')
  var servicio_observaciones = button.data('servicio_observaciones')
  var servicio_actualizacion = button.data('servicio_actualizacion')
  var sede = button.data('sede')
  var horario = button.data('horario')
  var direccion = button.data('direccion')
  var ciudad = button.data('ciudad')
  var tipo_ciudad = button.data('tipo_ciudad')
  var contratista = button.data('contratista')
  var desplazamiento = button.data('desplazamiento')
  var sede_observaciones = button.data('sede_observaciones')
  var sede_actualizacion = button.data('sede_actualizacion')
  var c1_nombre_1 = button.data('c1_nombre_1')
  var c1_telefono_1 = button.data('c1_telefono_1')
  var c1_telefono_2 = button.data('c1_telefono_2')
  var c1_tipo = button.data('c1_tipo')
  var c1_correo = button.data('c1_correo')
  var c1_cargo = button.data('c1_cargo')
  var c1_last_update = button.data('c1_last_update')
  var c1_observaciones = button.data('c1_observaciones')
  var c2_nombre_1 = button.data('c2_nombre_1')
  var c2_telefono_1 = button.data('c2_telefono_1')
  var c2_telefono_2 = button.data('c2_telefono_2')
  var c2_tipo = button.data('c2_tipo')
  var c2_correo = button.data('c2_correo')
  var c2_cargo = button.data('c2_cargo')
  var c2_last_update = button.data('c2_last_update')
  var c2_observaciones = button.data('c2_observaciones')
  var nit = button.data('nit')
  var razon_social = button.data('razon_social')
  var atencion = button.data('atencion')
  var segmento = button.data('segmento')
  var cluster = button.data('cluster')
  var cnoc = button.data('cnoc')
  var cgp = button.data('cgp')
  var observaciones = button.data('observaciones')
  var modal = $(this)
  modal.find('.modal-body #ds_servicio').val(ds_servicio)
  modal.find('.modal-body #estado_servicio').val(estado_servicio)
  modal.find('.modal-body #criticidad').val(criticidad)
  modal.find('.modal-body #fecha_alta').val(fecha_alta)
  modal.find('.modal-body #fecha_baja').val(fecha_baja)
  modal.find('.modal-body #abonado').val(abonado)
  modal.find('.modal-body #ans').val(ans)
  modal.find('.modal-body #bw').val(bw)
  modal.find('.modal-body #nombre_dslam').val(nombre_dslam)
  modal.find('.modal-body #ip_dslam').val(ip_dslam)
  modal.find('.modal-body #cta_padre').val(cta_padre)
  modal.find('.modal-body #dir_tipo').val(dir_tipo)
  modal.find('.modal-body #pool_ip').val(pool_ip)
  modal.find('.modal-body #pot').val(pot)
  modal.find('.modal-body #pto_adsl').val(pto_adsl)
  modal.find('.modal-body #tecnologia').val(tecnologia)
  modal.find('.modal-body #nombre_nisip').val(nombre_nisip)
  modal.find('.modal-body #ip_nisip').val(ip_nisip)
  modal.find('.modal-body #vlan_nisip').val(vlan_nisip)
  modal.find('.modal-body #vrf_nisip').val(vrf_nisip)
  modal.find('.modal-body #medio').val(medio)
  modal.find('.modal-body #marca_modem').val(marca_modem)
  modal.find('.modal-body #modelo_modem').val(modelo_modem)
  modal.find('.modal-body #serial_modem').val(serial_modem)
  modal.find('.modal-body #servicio_observaciones').val(servicio_observaciones)
  modal.find('.modal-body #servicio_actualizacion').val(servicio_actualizacion)
  modal.find('.modal-body #sede').val(sede)
  modal.find('.modal-body #horario').val(horario)
  modal.find('.modal-body #direccion').val(direccion)
  modal.find('.modal-body #ciudad').val(ciudad)
  modal.find('.modal-body #tipo_ciudad').val(tipo_ciudad)
  modal.find('.modal-body #contratista').val(contratista)
  modal.find('.modal-body #desplazamiento').val(desplazamiento)
  modal.find('.modal-body #sede_observaciones').val(sede_observaciones)
  modal.find('.modal-body #sede_actualizacion').val(sede_actualizacion)
  modal.find('.modal-body #c1_nombre_1').val(c1_nombre_1)
  modal.find('.modal-body #c1_telefono_1').val(c1_telefono_1)
  modal.find('.modal-body #c1_telefono_2').val(c1_telefono_2)
  modal.find('.modal-body #c1_tipo').val(c1_tipo)
  modal.find('.modal-body #c1_correo').val(c1_correo)
  modal.find('.modal-body #c1_cargo').val(c1_cargo)
  modal.find('.modal-body #c1_last_update').val(c1_last_update)
  modal.find('.modal-body #c1_observaciones').val(c1_observaciones)
  modal.find('.modal-body #c2_nombre_1').val(c2_nombre_1)
  modal.find('.modal-body #c2_telefono_1').val(c2_telefono_1)
  modal.find('.modal-body #c2_telefono_2').val(c2_telefono_2)
  modal.find('.modal-body #c2_tipo').val(c2_tipo)
  modal.find('.modal-body #c2_correo').val(c2_correo)
  modal.find('.modal-body #c2_cargo').val(c2_cargo)
  modal.find('.modal-body #c2_last_update').val(c2_last_update)
  modal.find('.modal-body #c2_observaciones').val(c2_observaciones)
  modal.find('.modal-body #nit').val(nit)
  modal.find('.modal-body #razon_social').val(razon_social)
  modal.find('.modal-body #atencion').val(atencion)
  modal.find('.modal-body #segmento').val(segmento)
  modal.find('.modal-body #cluster').val(cluster)
  modal.find('.modal-body #cnoc').val(cnoc)
  modal.find('.modal-body #cgp').val(cgp)
  modal.find('.modal-body #observaciones').val(observaciones)
  $('.alert').hide();//Oculto alert
})


$('#dataView_e1').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Botón que activó el modal
  var piloto = button.data('piloto') // Extraer la información de atributos de datos
  var estado_servicio = button.data('estado_servicio')
  var criticidad = button.data('criticidad')
  var fecha_alta = button.data('fecha_alta')
  var fecha_baja = button.data('fecha_baja')
  var tipo_servicio = button.data('tipo_servicio')
  var numero_canales = button.data('numero_canales')
  var marca_equipo = button.data('marca_equipo')
  var servicio_observaciones = button.data('servicio_observaciones')
  var servicio_actualizacion = button.data('servicio_actualizacion')
  var sede = button.data('sede')
  var horario = button.data('horario')
  var direccion = button.data('direccion')
  var ciudad = button.data('ciudad')
  var tipo_ciudad = button.data('tipo_ciudad')
  var contratista = button.data('contratista')
  var desplazamiento = button.data('desplazamiento')
  var sede_observaciones = button.data('sede_observaciones')
  var sede_actualizacion = button.data('sede_actualizacion')
  var c1_nombre_1 = button.data('c1_nombre_1')
  var c1_telefono_1 = button.data('c1_telefono_1')
  var c1_telefono_2 = button.data('c1_telefono_2')
  var c1_tipo = button.data('c1_tipo')
  var c1_correo = button.data('c1_correo')
  var c1_cargo = button.data('c1_cargo')
  var c1_last_update = button.data('c1_last_update')
  var c1_observaciones = button.data('c1_observaciones')
  var c2_nombre_1 = button.data('c2_nombre_1')
  var c2_telefono_1 = button.data('c2_telefono_1')
  var c2_telefono_2 = button.data('c2_telefono_2')
  var c2_tipo = button.data('c2_tipo')
  var c2_correo = button.data('c2_correo')
  var c2_cargo = button.data('c2_cargo')
  var c2_last_update = button.data('c2_last_update')
  var c2_observaciones = button.data('c2_observaciones')
  var nit = button.data('nit')
  var razon_social = button.data('razon_social')
  var atencion = button.data('atencion')
  var segmento = button.data('segmento')
  var cluster = button.data('cluster')
  var cnoc = button.data('cnoc')
  var cgp = button.data('cgp')
  var observaciones = button.data('observaciones')
  var modal = $(this)
  modal.find('.modal-body #piloto').val(piloto)
  modal.find('.modal-body #estado_servicio').val(estado_servicio)
  modal.find('.modal-body #criticidad').val(criticidad)
  modal.find('.modal-body #fecha_alta').val(fecha_alta)
  modal.find('.modal-body #fecha_baja').val(fecha_baja)
  modal.find('.modal-body #numero_canales').val(numero_canales)
  modal.find('.modal-body #marca_equipo').val(marca_equipo)
  modal.find('.modal-body #servicio_observaciones').val(servicio_observaciones)
  modal.find('.modal-body #servicio_actualizacion').val(servicio_actualizacion)
  modal.find('.modal-body #sede').val(sede)
  modal.find('.modal-body #horario').val(horario)
  modal.find('.modal-body #direccion').val(direccion)
  modal.find('.modal-body #ciudad').val(ciudad)
  modal.find('.modal-body #tipo_ciudad').val(tipo_ciudad)
  modal.find('.modal-body #contratista').val(contratista)
  modal.find('.modal-body #desplazamiento').val(desplazamiento)
  modal.find('.modal-body #sede_observaciones').val(sede_observaciones)
  modal.find('.modal-body #sede_actualizacion').val(sede_actualizacion)
  modal.find('.modal-body #c1_nombre_1').val(c1_nombre_1)
  modal.find('.modal-body #c1_telefono_1').val(c1_telefono_1)
  modal.find('.modal-body #c1_telefono_2').val(c1_telefono_2)
  modal.find('.modal-body #c1_tipo').val(c1_tipo)
  modal.find('.modal-body #c1_correo').val(c1_correo)
  modal.find('.modal-body #c1_cargo').val(c1_cargo)
  modal.find('.modal-body #c1_last_update').val(c1_last_update)
  modal.find('.modal-body #c1_observaciones').val(c1_observaciones)
  modal.find('.modal-body #c2_nombre_1').val(c2_nombre_1)
  modal.find('.modal-body #c2_telefono_1').val(c2_telefono_1)
  modal.find('.modal-body #c2_telefono_2').val(c2_telefono_2)
  modal.find('.modal-body #c2_tipo').val(c2_tipo)
  modal.find('.modal-body #c2_correo').val(c2_correo)
  modal.find('.modal-body #c2_cargo').val(c2_cargo)
  modal.find('.modal-body #c2_last_update').val(c2_last_update)
  modal.find('.modal-body #c2_observaciones').val(c2_observaciones)
  modal.find('.modal-body #nit').val(nit)
  modal.find('.modal-body #razon_social').val(razon_social)
  modal.find('.modal-body #atencion').val(atencion)
  modal.find('.modal-body #segmento').val(segmento)
  modal.find('.modal-body #cluster').val(cluster)
  modal.find('.modal-body #cnoc').val(cnoc)
  modal.find('.modal-body #cgp').val(cgp)
  modal.find('.modal-body #observaciones').val(observaciones)
  $('.alert').hide();//Oculto alert
})

$('#dataView_contactos').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Botón que activó el modal
  var nombres_apellidos = button.data('nombres_apellidos') // Extraer la información de atributos de datos
  var telefono_1 = button.data('telefono_1')
  var extension_1 = button.data('extension_1')
  var telefono_2 = button.data('telefono_2')
  var extension_2 = button.data('extension_2')
  var tipo_contacto = button.data('tipo_contacto')
  var correo = button.data('correo')
  var cargo = button.data('cargo')
  var direccion = button.data('direccion')
  var ciudad = button.data('ciudad')
  var nit_cliente = button.data('nit_cliente')
  var nombre_cliente = button.data('nombre_cliente')
  var last_update = button.data('last_update')
  var observaciones = button.data('observaciones')
  var atencion = button.data('atencion')
  var segmento = button.data('segmento')
  var cluster = button.data('cluster')
  var cnoc = button.data('cnoc')
  var cgp = button.data('cgp')
  var cliente_observaciones = button.data('cliente_observaciones')
  var modal = $(this)
  modal.find('.modal-body #nombres_apellidos').val(nombres_apellidos)
  modal.find('.modal-body #telefono_1').val(telefono_1)
  modal.find('.modal-body #extension_1').val(extension_1)
  modal.find('.modal-body #telefono_2').val(telefono_2)
  modal.find('.modal-body #extension_2').val(extension_2)
  modal.find('.modal-body #tipo_contacto').val(tipo_contacto)
  modal.find('.modal-body #correo').val(correo)
  modal.find('.modal-body #cargo').val(cargo)
  modal.find('.modal-body #direccion').val(direccion)
  modal.find('.modal-body #ciudad').val(ciudad)
  modal.find('.modal-body #nit_cliente').val(nit_cliente)
  modal.find('.modal-body #nombre_cliente').val(nombre_cliente)
  modal.find('.modal-body #last_update').val(last_update)
  modal.find('.modal-body #observaciones').val(observaciones)
  modal.find('.modal-body #atencion').val(atencion)
  modal.find('.modal-body #segmento').val(segmento)
  modal.find('.modal-body #cluster').val(cluster)
  modal.find('.modal-body #cnoc').val(cnoc)
  modal.find('.modal-body #cgp').val(cgp)
  modal.find('.modal-body #cliente_observaciones').val(cliente_observaciones)
  
  $('.alert').hide();//Oculto alert
})

$('#dataReset').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Botón que activó el modal
  var id_usuario = button.data('id_usuario') // Extraer la información de atributos de datos
  var defaul_password = button.data('defaul_password') // Extraer la información de atributos de datos
  
  var modal = $(this)
  modal.find('.modal-body #id_usuario').val(id_usuario)
  modal.find('.modal-body #defaul_password').val(defaul_password)
  
  $('.alert').hide();//Oculto alert
})

$( "#reset" ).submit(function( event ) {
    var parametros = $(this).serialize();
       $.ajax({
          type: "POST",
          url: "reset_password.php",
          data: parametros,
           beforeSend: function(objeto){
            $("#datos_ajax").html("Mensaje: Cargando...");
            },
          success: function(datos){
          $("#datos_ajax").html(datos);
          
          load(1);

          }

      });
      event.preventDefault();
    });

$( "#cerrar_gestion" ).submit(function( event ) {
    var parametros = $(this).serialize();
       $.ajax({
          type: "POST",
          url: "cerrar_gestion.php",
          data: parametros,
           beforeSend: function(objeto){
            $("#datos_ajax").html("Mensaje: Cargando...");
            },
          success: function(datos){
          $("#datos_ajax").html(datos);
          
          load(1);

          }

      });
      event.preventDefault();
    });